#!/bin/bash

#pyenv init
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

#enter virtual environment
pyenv activate venv-default

#execution
if [ "$#" = "0" ]; then
    stegpy -h
    exit 0
fi
stegpy "$@"
err_lvl=$?

#leave virtual environment
source deactivate

exit $err_lvl
