#!/bin/bash

#pyenv init
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

#enter virtual environment
pyenv activate venv-default

if [ ! -f "/home/wineuser/.local/bin/stegano-steganalysis-statistics" ]; then
    echo "Installing stegano, this might take a while..."
    pipx ensurepath > /dev/null 2>&1
    pipx install stegano > /dev/null 2>&1
fi
if [ ! -f "/home/wineuser/.local/bin/stegano-steganalysis-statistics" ]; then
    echo "Error: stegano installation failed!"
    exit 1
fi
if [ "$#" = "0" ]; then
    /home/wineuser/.local/bin/stegano-steganalysis-statistics -h
    exit 0
fi
/home/wineuser/.local/bin/stegano-steganalysis-statistics "$@"
err_lvl=$?

#leave virtual environment
source deactivate

exit $err_lvl
