#!/bin/bash

IMAGE_NAME="interactive_stego"
BASE_PATH="./interactive_stego_docker"

if [ ! -d "$BASE_PATH/docker-wine" ]; then
    echo "Downloading base repository..."
    git clone https://github.com/scottyhardy/docker-wine $BASE_PATH/docker-wine 2> /dev/null
fi

echo "Patching Dockerfile..."
rm -f "$BASE_PATH/docker-wine/Dockerfile"
cp "$BASE_PATH/Dockerfile.patch" "$BASE_PATH/docker-wine/Dockerfile"
if [ -d "$BASE_PATH/docker-wine/bin" ]; then
    rm -fdr "$BASE_PATH/docker-wine/bin"
fi
cp -R "$BASE_PATH/bin" "$BASE_PATH/docker-wine/bin"
if [ -d "$BASE_PATH/docker-wine/home" ]; then
    rm -fdr "$BASE_PATH/docker-wine/home"
fi
if [ ! -d "$BASE_PATH/home/io" ]; then
    mkdir "$BASE_PATH/home/io"
fi
cp -R "$BASE_PATH/home" "$BASE_PATH/docker-wine/home"
cp "$BASE_PATH/apt.txt" "$BASE_PATH/docker-wine/packages.txt"
cp "$BASE_PATH/pip.txt" "$BASE_PATH/docker-wine/requirements.txt"

echo "Building image..."
DOCKER_BUILDKIT=1 docker build \
    --tag $IMAGE_NAME \
    $BASE_PATH/docker-wine
err_lvl=$?
if [ "$err_lvl" = "0" ]; then
    echo "Build was successful!"
    exit 0
else
    echo "Build failed with error code $err_lvl!"
    exit $err_lvl
fi
