FROM scottyhardy/docker-remote-desktop:latest AS base

FROM base AS wine
    RUN apt-get update
    RUN apt-get install -y gnupg wget

    ARG WINE_BRANCH="stable"
    RUN wget -nv -O- https://dl.winehq.org/wine-builds/winehq.key | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add - \
        && echo "deb https://dl.winehq.org/wine-builds/ubuntu/ $(grep VERSION_CODENAME= /etc/os-release | cut -d= -f2) main" >> /etc/apt/sources.list
    RUN dpkg --add-architecture i386
    RUN apt-get update
    RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y --install-recommends winehq-${WINE_BRANCH}
    RUN rm -rf /var/lib/apt/lists/*

    RUN wget -nv -O /usr/bin/winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks \
        && chmod +x /usr/bin/winetricks

    COPY download_gecko_and_mono.sh /root/download_gecko_and_mono.sh
    RUN chmod +x /root/download_gecko_and_mono.sh \
        && /root/download_gecko_and_mono.sh "$(wine --version | sed -E 's/^wine-//')"

    # create wine32 and wine64 prefixes
    RUN mkdir "/home/wineuser"
    RUN WINEPREFIX="/home/wineuser/.wine32" WINEARCH=win32 wine wineboot \
        && WINEPREFIX="/home/wineuser/.wine32" WINEARCH=win32 winetricks -q dotnet40
    RUN WINEPREFIX="/home/wineuser/.wine64" wine wineboot

FROM wine AS apt-packages
    COPY packages.txt /home/packages.txt

    # install dependencies specified in 'apt.txt'
    RUN apt-get update
    RUN DEBIAN_FRONTEND="noninteractive" xargs apt-get -y --no-install-recommends install < /home/packages.txt

    RUN rm -rf /var/lib/apt/lists/* && rm -f /home/packages.txt

FROM apt-packages AS python-environment
    # install pyenv
    ENV PYENV_ROOT="/home/wineuser/.pyenv"
    ENV PATH="$PYENV_ROOT/bin:$PATH"
    ENV PATH="$PYENV_ROOT/shims:$PATH"
    RUN curl https://pyenv.run | bash

    # install python versions and create environments
    RUN pyenv install 2.7.18
    RUN pyenv virtualenv 2.7.18 venv-2718
    RUN pyenv install 3.10.13
    RUN pyenv virtualenv 3.10.13 venv-31013
    RUN pyenv install 3.12.13
    RUN pyenv virtualenv 3.12.13 venv-default

    # install tools specified in 'pip.txt'dggggg
    COPY requirements.txt /home/requirements.txt
    RUN eval "$(pyenv init --path)" \
        && eval "$(pyenv init -)" \
        && pyenv shell venv-default \
        && pip install --upgrade pip \
        && pip install --upgrade -r /home/requirements.txt
    RUN rm -f /home/requirements.txt

FROM python-environment AS git-repositories
    COPY ./bin /home/bin

    RUN git clone https://github.com/danielcardeenas/AudioStego.git /home/bin/AudioStego \
        && mkdir /home/bin/AudioStego/build \
        && cd /home/bin/AudioStego/build \
        && cmake .. && make \
        && cd /
    RUN git clone https://github.com/livz/cloacked-pixel.git /home/bin/cloackedpixel
    RUN git clone https://github.com/oneplus-x/DeepSound-2.0.git /home/bin/deepsound
    #RUN wget -O /home/bin/DeepSoundSetup.msi https://github.com/Jpinsoft/DeepSound/releases/download/v2.1.2401.03/DeepSound_2_1.msi
    RUN git clone https://github.com/matthewgao/F5-steganography.git /home/bin/f5
    RUN unzip /home/bin/hidereveal-bin-1.7.0.zip -d /home/bin/hidereveal
    RUN git clone https://github.com/RobinDavid/LSB-Steganography.git /home/bin/lsbstego
    RUN git clone https://github.com/ImageMagick/ImageMagick.git /home/bin/magick \
        && cd /home/bin/magick \
        && ./configure --with-modules \
        && make && make install \
        && ldconfig /usr/local/lib \
        && cd /
    RUN git clone https://github.com/bh-8/hiwi-jpeg-investigator.git /home/bin/jpeg-investigator
    RUN git clone https://github.com/h3xx/jphs.git /home/bin/jphs \
        && rm -fdr /home/bin/jphs/jpeg-8a/ \
        && tar -xvzf /home/bin/jphs-jpeg-8a.tar.gz.patch -C /home/bin/jphs \
        && rm -f /home/bin/jphs/jpseek.c \
        && cp /home/bin/jphs-jpseek.c.patch /home/bin/jphs/jpseek.c \
        && cd /home/bin/jphs \
        && cc -O2 -I./jpeg-8a -c -o jphide.o jphide.c \
        && cc -O2 -I./jpeg-8a -c -o jpseek.o jpseek.c \
        && cc -O2 -c -o bf.o bf.c \
        && cc jphide.o bf.o -o jphide -ljpeg \
        && cc jpseek.o bf.o -o jpseek -ljpeg \
        && cd /
    RUN wget -O /home/bin/jsteg-linux-amd64 https://github.com/lukechampine/jsteg/releases/download/v0.3.0/jsteg-linux-amd64 \
        && chmod +x /home/bin/jsteg-linux-amd64
    RUN git clone https://git.code.sf.net/p/mp3filestructureanalyser/code /home/bin/mp3-analyzer
    RUN unzip /home/bin/MP3Stego_1_1_19.zip -d /home/bin/MP3Stego || :
    RUN unzip /home/bin/mp3stegz-1.0.zip -d /home/bin
    RUN unzip /home/bin/OpenPuff_release.zip -d /home/bin
    RUN wget -O /home/bin/OpenStego.deb https://github.com/syvaidya/openstego/releases/download/openstego-0.8.6/openstego_0.8.6-1_all.deb \
        && dpkg -i /home/bin/OpenStego.deb
    RUN git clone https://github.com/mattkwan-zz/snow.git /home/bin/snow \
        && cd /home/bin/snow \
        && make \
        && cd /
    RUN wget -O /home/bin/SonicVisualiser.AppImage https://github.com/sonic-visualiser/sonic-visualiser/releases/download/sv_v4.5.2/SonicVisualiser-4.5.2-x86_64.AppImage \
        && chmod a+x /home/bin/SonicVisualiser.AppImage
    RUN git clone https://github.com/solusipse/spectrology.git /home/bin/spectrology
    RUN tar -xvzf /home/bin/Steg-1.1.0.0-Linux-x64.tgz -C /home/bin \
        && chown -R 1010:1010 /home/bin/Steg-1.1.0.0-Linux-x64/ \
        && chmod a+x /home/bin/Steg-1.1.0.0-Linux-x64/Steg-1.1.0.0-x64.AppImage
    RUN tar -xvzf /home/bin/steganabara-1.1.1.tar.gz -C /home/bin
    # TODO: fix:
    #RUN git clone https://github.com/abeluck/stegdetect.git /home/bin/stegdetect \
    #    && cd /home/bin/stegdetect \
    #    && autoreconf -f -i \
    #    && linux32 ./configure \
    #    && linux32 make \
    #    && cd /
    RUN tar -xvzf /home/bin/stegonaut.tar.gz -C /home/bin \
        && cd /home/bin/stegonaut \
        && npm install \
        && cd /
    RUN git clone https://github.com/zed-0xff/zsteg.git /home/bin/zsteg \
        && cd /home/bin/zsteg \
        && gem install zsteg \
        && cd /
    RUN rm -f \
        /home/bin/DeepSound-2.0-master.zip \
        /home/bin/hidereveal-bin-1.7.0.zip \
        /home/bin/jphs-jpeg-8a.tar.gz.patch \
        /home/bin/jphs-jpseek.c.patch \
        /home/bin/MP3Stego_1_1_19.zip \
        /home/bin/mp3stegz-1.0.zip \
        /home/bin/OpenPuff_release.zip \
        /home/bin/OpenStego.deb \
        /home/bin/Steg-1.1.0.0-Linux-x64.tgz \
        /home/bin/steganabara-1.1.1.tar.gz \
        /home/bin/stegonaut.tar.gz

FROM git-repositories AS config
    RUN locale-gen en_US.UTF-8
    ENV LANG=en_US.UTF-8
    COPY pulse-client.conf /root/pulse/client.conf
    COPY entrypoint.sh /usr/bin/entrypoint

    COPY ./home /home/wineuser
    RUN find /home/wineuser -mindepth 1 -maxdepth 1 -type f -exec chmod +x {} \;

    WORKDIR /home/wineuser
